version: '3.7'

services:
  server:
    image: library/traefik:1.7
    command:
      - "--debug"
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.watch"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8443:443
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.port: 8080
        traefik.frontend.rule: "Host: traefik.35.246.71.61.nip.io,traefik.34.105.253.107.nip.io,traefik.35.242.172.150.nip.io"
        traefik.docker.network: proxy


networks:
  proxy:
    external: true

