version: "3.7"

services:

  redis:
    image: redis
    networks:
      - backend

  front:
    image: kpeiruza/docker-php-mysql-redis
    networks:
      - proxy
      - backend
    ports:
      - "80"
    deploy:
      replicas: 10
      endpoint_mode: vip
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host: ${HOST_LIST}"
        traefik.docker.network: 'proxy'

networks:
  proxy:
    external: true
  backend:
    driver: 'overlay'
