version: '3.7'
services:
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - 3000:3000
    volumes:
      - /data/grafana:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.labels.grafana == true
  
  influxdb:
    image: influxdb:1.3.5-alpine
    configs:
      - source: influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - /data/influxdb:/var/lib/influxdb
    deploy:
      placement:
        constraints:
          - node.labels.influxdb == true
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome1 

  telegraf:
    image: telegraf:1.4.0
    hostname: "{{.Node.ID}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf.conf
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global

networks:
  monitoring:

configs:
  telegraf.conf:
    file: ./telegraf/telegraf.conf
  influxdb.conf:
    file: ./influxdb/influxdb.conf