# Based on: https://wmartins.github.io/2017/10/creating-a-monitoring-stack-with-docker-swarm-grafana-influxdb-and-telegraf/

version: '3.7'
services:
  grafana:
    image: grafana/grafana:4.5.2
    networks:
     - monitoring
     - proxy
    #ports:
    #  - 3000:3000
    volumes:
      - /opt/docker/monitor/volumes/grafana:/var/lib/grafana
    deploy:
      labels:
        traefik.port: 3000
        traefik.frontend.rule: "Host: grafana.${IP1}.nip.io,grafana.${IP2}.nip.io,grafana.${IP3}.nip.io"
        traefik.docker.network: proxy
  
  influxdb:
    image: influxdb:1.3.5-alpine
    configs:
      - source: influxdb
        target: /etc/influxdb/influxdb.conf
    volumes:
      - /opt/docker/monitor/volumes/influxdb:/var/lib/influxdb
    networks:
     - monitoring
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password 

  telegraf:
    image: telegraf:1.4.0
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf
        target: /etc/telegraf/telegraf.conf
    networks:
     - monitoring
    deploy:
      mode: global

networks:
  monitoring:
  proxy: 
    external: true

configs:
  telegraf:
    file: ./telegraf.conf
  influxdb:
    file: ./influxdb.conf