version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network

      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug

    networks:
     - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  web:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /opt/docker/portainer/volumes/portainer:/data
    environment:
     - TZ=Europe/Madrid
    networks:
     - backend
     - proxy
    #ports:
    # - 9000:9000
    deploy:
      labels:
        traefik.port: 9000
        traefik.frontend.rule: "Host: ${HOST_LIST}"
        traefik.docker.network: proxy
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  backend: 
  proxy: 
    external: true

